[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PYTHON_VERSION = "3.8"  # Using a specific Python version instead of "false"