// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehukrbciwnbqddxrfksz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodWtyYmNpd25icWRkeHJma3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMzQ2OTAsImV4cCI6MjA0OTgxMDY5MH0.Fzf6fW7pylB7KavutVEHX7pTDat1s48QOO5o50o_Yc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);